apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo-cruise-ship
  namespace: demo-cruise-ship
spec:
  replicas: 1
  selector:
    matchLabels:
      demo: cruise-ship
  serviceName: demo
  template:
    metadata:
      labels:
        demo: cruise-ship
    spec:
      containers:
        - image: DOCKER_IMAGE
          imagePullPolicy: Always
          name: demo
          ports:
            - containerPort: 9001
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
